Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - CustomSiteConfig

SilverStripe\Security\Group:
  extensions:
    - GroupExtension

SilverStripe\Security\Member:
  extensions:
    - MemberExtension
