---
Name: xxx
After: framework/_config/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'draf-rb//$Action/$ID/$Name': 'DraftRBController'
    'test//$Action/$ID/$Name': 'TestController'
    'user': 'UserController'
    'helper': 'HelperController'
    'rb': 'RBController'
    'po': 'POController'
    'ta': 'MyTaskController'
    'rj': 'RejectedController'
    'prfl': 'ProfileController'
